<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
      <key>items</key>
      <array>
        <dict>
           <key>assets</key>
           <array>
             <dict>
               <key>kind</key>
               <string>software-package</string>
               <key>url</key>
               <string><![CDATA[https://github.com/V2RaySSR/ios/releases/download/Shadowrocket/Shadowrocket-2.1.11.ipa]]></string>
             </dict>
             <dict>
               <key>kind</key>
               <string>display-image</string>
               <key>needs-shine</key>
               <integer>0</integer>
               <key>url</key>
               <string><![CDATA[http://a182.phobos.apple.com/us/r30/Purple118/v4/c9/0e/83/c90e835f-4797-fe0b-3842-67497901be4c/CRV_AP_150x90.jpeg]]></string>
             </dict>
             <dict>
               <key>kind</key>
               <string>full-size-image</string>
               <key>needs-shine</key>
               <true/>
               <key>url</key>
               <string><![CDATA[http://a182.phobos.apple.com/us/r30/Purple118/v4/c9/0e/83/c90e835f-4797-fe0b-3842-67497901be4c/CRV_AP_150x90.jpeg]]></string>
             </dict>
           </array>
           <key>metadata</key>
           <dict>
             <key>bundle-identifier</key>
             <string>com.liguangming.Shadowrocket</string>
             <key>bundle-version</key>
             <string><![CDATA[1.0.0]]></string>
             <key>kind</key>
             <string>software</string>
             <key>title</key>
             <string><![CDATA[Shadowrocket]]></string>
           </dict>
        </dict>
      </array>
  </dict>
</plist>
